server:
  # 之后所有的图书服务节点就81XX端口
  port: 8301
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://1.12.238.40:3306/book
    url: jdbc:mysql://localhost:3306/book
    username: root
    password: 458412625
  # 应用名称 bookservice
  application:
    name: borrowservice
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: localhost:8848